baseURL = "https://NickS55.github.io/"
languageCode = "en-us"
title = "Nicholas Sadd | Baseball Player / Software Engineer"
theme = "hugo-tanka2"

[params]
  sitename = "Nicholas Sadd"
  description = "Software Engineer | Baseball Player"
  faviconfile = "images/favicon.png"
  highlightjs = true
  progressively = false
# commentsrepo = "user/repo"

    github = "NickS55"
    linkedIn = "nicholas-sadd-114b43163/"
    twitter = "NicholasSadd"
    contact = "nicholassadd@gmail.com"

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "Resume"
    url = "/resume/"
    weight = 2
[[menu.primary]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.primary]]
    name = "Writings"
    url = "/posts/"
    weight = 4

